export const LOAD_LECTURES_SUCCESS = 'LOAD_LECTURES_SUCCESS';
export const LOAD_CLASSROOMS_SUCCESS = 'LOAD_CLASSROOMS_SUCCESS';
export const LOAD_SCHOOLS_SUCCESS = 'LOAD_SCHOOLS_SUCCESS';

export const LOAD_LECTURES_FOR_CLASSROOM_SUCCESS = 'LOAD_LECTURES_FOR_CLASSROOM_SUCCESS';
export const LOAD_LECTURES_FOR_SCHOOL_SUCCESS = 'LOAD_LECTURES_FOR_SCHOOL_SUCCESS';

export const CREATE_LECTURE_SUCCESS = 'CREATE_LECTURE_SUCCESS';
export const UPDATE_LECTURE_SUCCESS = 'UPDATE_LECTURE_SUCCESS';
export const DELETE_LECTURE_SUCCESS = 'DELETE_LECTURE_SUCCESS';

export const CREATE_SCHOOL_SUCCESS = 'CREATE_SCHOOL_SUCCESS';
export const UPDATE_SCHOOL_SUCCESS = 'UPDATE_SCHOOL_SUCCESS';
export const DELETE_SCHOOL_SUCCESS = 'DELETE_SCHOOL_SUCCESS';
